# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique='True', verbose_name='URL')),
                ('yt_id', models.CharField(max_length=50, unique='True', verbose_name='youtube ID')),
                ('title', models.CharField(max_length=150, unique='True', verbose_name='Tytu\u0142')),
                ('count', models.IntegerField(default='0', verbose_name='Delay')),
                ('played', models.IntegerField(default='0', verbose_name='Odtworzenie')),
                ('new', models.IntegerField(default='1', verbose_name='Czy nowy')),
                ('stoped', models.IntegerField(default='0', verbose_name='Czy zablokowany')),
            ],
            options={
                'verbose_name': 'Rekord',
                'verbose_name_plural': 'Rekordy',
            },
        ),
    ]
