# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='stoped',
            new_name='isstoped',
        ),
    ]
