# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20171030_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='isstoped',
        ),
        migrations.AddField(
            model_name='sound',
            name='stoped',
            field=models.IntegerField(default='0', verbose_name='Zablokowany'),
        ),
    ]
