# Generated by Django 5.1.2 on 2024-10-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20171030_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
    ]
